import React from 'react';
import { Route, Routes, useNavigate } from 'react-router';
import { useState, useEffect } from 'react';
import Signup from './components/Signup';
import Login from './components/Login';
import Main from './components/Main';
import Missing from './components/Missing';

const App = () => {
  const [items,setItems]=useState([
    {id:1,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:2,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:3,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:4,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:5,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:6,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:7,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:8,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:9,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:10,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:11,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:12,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:13,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:14,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:15,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:16,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:17,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:18,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:18,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:19,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:20,type:'human',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
    {id:21,type:'bot',content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae sint ducimus praesentium aliquid, quidem commodi quasi magnam veritatis unde. Veritatis consequatur autem numquam voluptatem reprehenderit consequuntur assumenda aut totam iste eos! Cumque sed, totam aut assumenda quam consequatur laudantium perspiciatis, officiis quod odit ullam asperiores, pariatur aliquam facilis quisquam voluptate.'},
  ])
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();



  return (
    <div className='font-bold'>
      <Routes>
        <Route path='/' element={<Main items={items} />} />
        <Route path='/signup' element={<Signup email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={error} setError={setError} navigate={navigate} />} />
        <Route path='/login' element={<Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={error} setError={setError} navigate={navigate} />} />
        <Route path='*' element={<Missing />} />
      </Routes>
    </div>
  );
};

export default App;